print('Num: %1.2f' % 13.114)
print('Num: %1.0f' % 13.114)
print('Num: %1.5f' % 13.114)
print('Num: %10.2f' % 13.114)
print('Num: %25.2f' % 13.114)
print('Here is a number: %s. Here is a string: %s' % (123.1, 'hi'))
print('Here is a number: %r. Here is a string: %r' % (123.1, 'hi'))
print('First: %s, Second: %1.2f, Third: %r' % ('hello', 1.342, 22))
print('This is a %s or a %s' % ('bacon', 'cat'))
print('This is a {a} or a {b}'.format(a='bacon', b='cat'))
print('A {p} will allways be a {p} is this {p} world'.format(p='dog'))
